// <auto-generated />
namespace myFinancas.MVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class cascadeTrue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cascadeTrue));
        
        string IMigrationMetadata.Id
        {
            get { return "201907251412111_cascadeTrue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
