// <auto-generated />
namespace myFinancas.MVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class inicial2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inicial2));
        
        string IMigrationMetadata.Id
        {
            get { return "201907081647081_inicial2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
